version: "3.5"

services:
  postgres15:
    container_name: postgres15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER = postgres
    image: postgres:14.3-alpine
